// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACascader: typeof import('ant-design-vue/es')['Cascader']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ARate: typeof import('ant-design-vue/es')['Rate']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    'Demo1.0': typeof import('./src/components/课堂练习/Demo1.0.vue')['default']
    Fivestar: typeof import('./src/components/课堂练习/Fivestar.vue')['default']
    Header: typeof import('./src/component/Header.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Product: typeof import('./src/components/homechild/Product.vue')['default']
    ReactiveData: typeof import('./src/components/01内部数据/ReactiveData.vue')['default']
    ReactiveData2: typeof import('./src/components/01内部数据/ReactiveData2.vue')['default']
    ReactiveData3: typeof import('./src/components/01内部数据/ReactiveData3.vue')['default']
    Reg: typeof import('./src/components/Reg.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    User: typeof import('./src/components/homechild/User.vue')['default']
  }
}
